packages: []

savePrefix: ""

minimumReleaseAge: 1440
minimumReleaseAgeExclude: []
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true

trustLockfile: false
blockExoticSubdeps: true
